Better error handling

diff --git a/runSynth b/runSynth
--- a/runSynth
+++ b/runSynth
@@ -8,17 +8,18 @@ fi
 ./checkMem
 command="python synth $@"
 echo $command
-pkill -f "$command" || echo "(wasn't already running so no need to kill)"
-rm ../synth_logs/$1.out || echo "(no previous log file to remove)"
-nohup $command >/dev/null 2>&1 & 
+pkill -f "$command" || echo ""
+rm -f ../synth_logs/$1.out
+nohup $command > ../synth_logs/$1.nohup 2>&1 & 
 sleep 1
 if [ -f ../synth_logs/$1.out ]; then
     echo -n `whoami` `date` "STARTED " >> ../synth_logs/jobs_run.txt
     echo $command >> ../synth_logs/jobs_run.txt
     echo "tail -f " ../synth_logs/$1.out
-    echo "(^C to stop monitoring - process will continue)"
+    echo "(^C stops monitoring - process will continue)"
     sleep 2
     tail -c+0 -f ../synth_logs/$1.out
 else 
-    echo "Something went wrong, to see what manually run " $command
+    echo "ERROR RUNNING SYNTH IN BACKGROUND. If below doesn't explain it, then manually re-run" $command
+    cat ../synth_logs/$1.nohup
 fi
